name: ci-build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            conda_platform: linux-64
            artifact_name: arango-cpp-linux
          - os: windows-latest
            conda_platform: win-64
            artifact_name: arango-cpp-windows
          - os: macos-latest
            conda_platform: osx-64
            artifact_name: arango-cpp-macos   

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: >
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          channels: conda-forge, defaults
          channel-priority: true

      - name: Configuring Conda Environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv

      - name: Building, Testing & Installing arango-cpp
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          conda activate arango-cpp
          mkdir .build && cd .build
          cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
          ninja
          ninja install

      - name: Building, Testing & Installing arango-cpp (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call conda activate arango-cpp || goto :eof
          mkdir .build && cd .build || goto :eof
          cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} || goto :eof
          ninja || goto :eof
          ninja install || goto :eof

